import { Product } from "../models/product.ts";

export const fakeProducts: Product[] = [
    {
        id: 1,
        name: "Jordan Flight Heritage",
        description:
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 20000,
        pictureUrl: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/589f5247-aa82-4cae-b154-4812e15a93c3/M+J+FLT+HRTG+DENIM+AOP+TOP.png",
        brand: "Nike",
        type: "Men's Denim Top",
        quantityInStock: 100,
    },
    {
        id: 2,
        name: "Jordan Brooklyn Fleece",
        description:
            "Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus.",
        price: 15000,
        pictureUrl: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/4a1675fe-847e-4307-babf-a4a307b953a6/M+J+ESS+FLC+PANT.png",
        brand: "Nike",
        type: "Men's Trousers\n",
        quantityInStock: 100,
    },
    {
        id: 3,
        name: "Sportswear",
        description:
            "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
        price: 18000,
        pictureUrl: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/13848eea-0863-4c37-b8f8-40c2af3222eb/M+NSW+BREAKING+LND+WR+JKT.png",
        brand: "Nike",
        type: "Men's Breakdancing Jacket\n",
        quantityInStock: 100,
    },
    {
        id: 4,
        name: "Club Alumni",
        description:
            "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.",
        price: 30000,
        pictureUrl: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ced18952-62d2-4b4e-8f15-dfd079a659f2/M+NK+CLUB+ALUMNI+HBR+FT+SHORT.png",
        brand: "Nike",
        type: "Men's French Terry Shorts",
        quantityInStock: 100,
    },
    {
        id: 5,
        name: "Sportswear Essentials",
        description:
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 25000,
        pictureUrl: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2c7d3ee7-c4d9-46e4-a95c-55a413de467b/W+NSW+ESSNTL+TEE+BF+LBR.png",
        brand: "Nike",
        type: "Women's T-Shirt",
        quantityInStock: 100,
    },
    {
        id: 6,
        name: "One Classic",
        description:
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 12000,
        pictureUrl: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/869f8d0b-1812-4cfe-b208-d20eb1557183/W+NK+ONE+CLASSIC+DF+STRPY+TANK.png",
        brand: "Nike",
        type: "Women's Dri-FIT Strappy Top",
        quantityInStock: 100,
    },
    {
        id: 7,
        name: "Core Blue Hat",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1000,
        pictureUrl: "../../images/products/hat-core1.png",
        brand: "NetCore",
        type: "Hats",
        quantityInStock: 100,
    },
    {
        id: 8,
        name: "Green React Woolen Hat",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 8000,
        pictureUrl: "../../images/products/hat-react1.png",
        brand: "React",
        type: "Hats",
        quantityInStock: 100,
    },
    {
        id: 9,
        name: "Purple React Woolen Hat",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1500,
        pictureUrl: "../../images/products/hat-react2.png",
        brand: "React",
        type: "Hats",
        quantityInStock: 100,
    },
    {
        id: 10,
        name: "Blue Code Gloves",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1800,
        pictureUrl: "../../images/products/glove-code1.png",
        brand: "VS Code",
        type: "Gloves",
        quantityInStock: 100,
    },
    {
        id: 11,
        name: "Green Code Gloves",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1500,
        pictureUrl: "../../images/products/glove-code2.png",
        brand: "VS Code",
        type: "Gloves",
        quantityInStock: 100,
    },
    {
        id: 12,
        name: "Purple React Gloves",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1600,
        pictureUrl: "../../images/products/glove-react1.png",
        brand: "React",
        type: "Gloves",
        quantityInStock: 100,
    },
    {
        id: 13,
        name: "Green React Gloves",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1400,
        pictureUrl: "../../images/products/glove-react2.png",
        brand: "React",
        type: "Gloves",
        quantityInStock: 100,
    },
    {
        id: 14,
        name: "Redis Red Boots",
        description:
            "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
        price: 25000,
        pictureUrl: "../../images/products/boot-redis1.png",
        brand: "Redis",
        type: "Boots",
        quantityInStock: 100,
    },
    {
        id: 15,
        name: "Core Red Boots",
        description:
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 18999,
        pictureUrl: "../../images/products/boot-core2.png",
        brand: "NetCore",
        type: "Boots",
        quantityInStock: 100,
    },
    {
        id: 16,
        name: "Core Purple Boots",
        description:
            "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.",
        price: 19999,
        pictureUrl: "../../images/products/boot-core1.png",
        brand: "NetCore",
        type: "Boots",
        quantityInStock: 100,
    },
    {
        id: 17,
        name: "Angular Purple Boots",
        description: "Aenean nec lorem. In porttitor. Donec laoreet nonummy augue.",
        price: 15000,
        pictureUrl: "../../images/products/boot-ang2.png",
        brand: "Angular",
        type: "Boots",
        quantityInStock: 100,
    },
    {
        id: 18,
        name: "Angular Blue Boots",
        description:
            "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
        price: 18000,
        pictureUrl: "../../images/products/boot-ang1.png",
        brand: "Angular",
        type: "Boots",
        quantityInStock: 100,
    },
];
