import { Product } from "../models/product.ts";

export const fakeProducts: Product[] = [
    {
        id: 1,
        name: "Angular Speedster Board 2000",
        description:
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 20000,
        pictureUrl: "../../public/products/sb-ang1.png",
        brand: "Angular",
        type: "Boards",
        quantityInStock: 100,
    },
    {
        id: 2,
        name: "Green Angular Board 3000",
        description:
            "Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus.",
        price: 15000,
        pictureUrl: "../../public/products/sb-ang2.png",
        brand: "Angular",
        type: "Boards",
        quantityInStock: 100,
    },
    {
        id: 3,
        name: "Core Board Speed Rush 3",
        description:
            "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
        price: 18000,
        pictureUrl: "../../public/products/sb-core1.png",
        brand: "NetCore",
        type: "Boards",
        quantityInStock: 100,
    },
    {
        id: 4,
        name: "Net Core Super Board",
        description:
            "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.",
        price: 30000,
        pictureUrl: "../../public/products/sb-core2.png",
        brand: "NetCore",
        type: "Boards",
        quantityInStock: 100,
    },
    {
        id: 5,
        name: "React Board Super Whizzy Fast",
        description:
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 25000,
        pictureUrl: "../../public/products/sb-react1.png",
        brand: "React",
        type: "Boards",
        quantityInStock: 100,
    },
    {
        id: 6,
        name: "Typescript Entry Board",
        description:
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 12000,
        pictureUrl: "../../public/products/sb-ts1.png",
        brand: "TypeScript",
        type: "Boards",
        quantityInStock: 100,
    },
    {
        id: 7,
        name: "Core Blue Hat",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1000,
        pictureUrl: "../../public/products/hat-core1.png",
        brand: "NetCore",
        type: "Hats",
        quantityInStock: 100,
    },
    {
        id: 8,
        name: "Green React Woolen Hat",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 8000,
        pictureUrl: "../../public/products/hat-react1.png",
        brand: "React",
        type: "Hats",
        quantityInStock: 100,
    },
    {
        id: 9,
        name: "Purple React Woolen Hat",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1500,
        pictureUrl: "../../public/products/hat-react2.png",
        brand: "React",
        type: "Hats",
        quantityInStock: 100,
    },
    {
        id: 10,
        name: "Blue Code Gloves",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1800,
        pictureUrl: "../../public/products/glove-code1.png",
        brand: "VS Code",
        type: "Gloves",
        quantityInStock: 100,
    },
    {
        id: 11,
        name: "Green Code Gloves",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1500,
        pictureUrl: "../../public/products/glove-code2.png",
        brand: "VS Code",
        type: "Gloves",
        quantityInStock: 100,
    },
    {
        id: 12,
        name: "Purple React Gloves",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1600,
        pictureUrl: "../../public/products/glove-react1.png",
        brand: "React",
        type: "Gloves",
        quantityInStock: 100,
    },
    {
        id: 13,
        name: "Green React Gloves",
        description:
            "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 1400,
        pictureUrl: "../../public/products/glove-react2.png",
        brand: "React",
        type: "Gloves",
        quantityInStock: 100,
    },
    {
        id: 14,
        name: "Redis Red Boots",
        description:
            "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
        price: 25000,
        pictureUrl: "../../public/products/boot-redis1.png",
        brand: "Redis",
        type: "Boots",
        quantityInStock: 100,
    },
    {
        id: 15,
        name: "Core Red Boots",
        description:
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
        price: 18999,
        pictureUrl: "../../public/products/boot-core2.png",
        brand: "NetCore",
        type: "Boots",
        quantityInStock: 100,
    },
    {
        id: 16,
        name: "Core Purple Boots",
        description:
            "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.",
        price: 19999,
        pictureUrl: "../../public/products/boot-core1.png",
        brand: "NetCore",
        type: "Boots",
        quantityInStock: 100,
    },
    {
        id: 17,
        name: "Angular Purple Boots",
        description: "Aenean nec lorem. In porttitor. Donec laoreet nonummy augue.",
        price: 15000,
        pictureUrl: "../../public/products/boot-ang2.png",
        brand: "Angular",
        type: "Boots",
        quantityInStock: 100,
    },
    {
        id: 18,
        name: "Angular Blue Boots",
        description:
            "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
        price: 18000,
        pictureUrl: "../../public/products/boot-ang1.png",
        brand: "Angular",
        type: "Boots",
        quantityInStock: 100,
    },
];
